language: python

python:
  - "3.6"

# command to install dependencies
install:
  - pip3 install pytest

# command to run tests
script:
  - pytest test.py --capture=fd

# disable sudo to speed up the build
sudo: false
